name: Publish to Nexus
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.target_commitish }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install bump2version
        run: |
          python -m pip install --upgrade pip
          git checkout main
          git config --global user.email "44278943+NexmoDev@users.noreply.github.com"
          git config --global user.name "NexmoDev"
          git config --global github.token ${{ secrets.GITHUB_TOKEN }}
          pip install bump2version
      - name: Bump Version
        run: bump2version --new-version ${{ github.event.release.tag_name }} patch &&
             git push --force